"""Production integration seams for explicitly promoted strategies."""

from twse_factor_lab.production.final_runtime import (
    AtomicRecommendationStore,
    CanonicalFundamentalRuntimeProvider,
    DailyRecommendation,
    FinalRuntimeError,
    build_daily_recommendations,
    build_real_snapshot_parity,
    build_three_runtime_snapshots,
    fresh_oos_audit,
    line_format,
    predeclared_snapshot_manifest,
    run_daily_fundamental,
    trading_session_rebalance_due,
    web_serialize,
)
from twse_factor_lab.production.fundamental import (
    CURRENT_PROMOTION_EVIDENCE,
    ENABLE_FLAG,
    FundamentalRuntimeAdapter,
    FundamentalStrategySpec,
    ProductionEligibility,
    ProductionEligibilityGate,
    ProductionIntegrationError,
    StrategyRegistration,
    StrategyRegistry,
    build_current_promotion_evidence,
    build_default_registry,
    compare_snapshots,
    explicit_enablement,
    normalize_recommendations,
    validate_pit_snapshot,
)

__all__ = [
    "CURRENT_PROMOTION_EVIDENCE",
    "ENABLE_FLAG",
    "FundamentalRuntimeAdapter",
    "FundamentalStrategySpec",
    "ProductionEligibility",
    "ProductionEligibilityGate",
    "ProductionIntegrationError",
    "StrategyRegistration",
    "StrategyRegistry",
    "build_default_registry",
    "build_current_promotion_evidence",
    "compare_snapshots",
    "explicit_enablement",
    "normalize_recommendations",
    "validate_pit_snapshot",
    "AtomicRecommendationStore",
    "CanonicalFundamentalRuntimeProvider",
    "DailyRecommendation",
    "FinalRuntimeError",
    "build_daily_recommendations",
    "build_real_snapshot_parity",
    "build_three_runtime_snapshots",
    "fresh_oos_audit",
    "line_format",
    "predeclared_snapshot_manifest",
    "run_daily_fundamental",
    "trading_session_rebalance_due",
    "web_serialize",
]
